coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true

ignore:
  - "src/**/*.spec.ts"
  - "src/**/*.interface.ts"
  - "src/**/*.dto.ts"
  - "src/**/*.entity.ts"
  - "src/main.ts"
  - "src/index.ts"
  - "src/**/*.config.ts"
  - "src/**/*.config.js"
  - "test/**/*"
  - "coverage/**/*"
  - "dist/**/*"
  - "node_modules/**/*"